# prettier-ignore
services:
  mongodb:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes: 
      - ./mongo:/data/db
    ports:
      - 27017:27017
  
  postgresdb:
    image: postgres:15.3
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432
